import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
// @ts-ignore
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const stem = localFont({
  src: [
    {
      path: "../public/fonts/Stem-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Stem-Regular.otf",
      weight: "400",
      style: "normal",
    },
  
  ],
  variable: "--font-mycustom",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${stem.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
